name: Kwiki-ModPerl
version: 0.09
abstract: enable Kwiki to work under mod_perl
author: Kang-min Liu <gugod@gugod.org>
license: perl
distribution_type: module
requires:
  perl: 5.6.1
  Kwiki: 0.32
  mod_perl: 0
no_index:
  directory:
    - inc
generated_by: Module::Install version 0.37
